name: Build and Release

on:
  push:
    {}
#    tags:
#      - '*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      - uses: actions/checkout@v4
      - name: build
        run: cmake build . --target exam_environment -DCMAKE_C_FLAGS="-Wall -Werror -pedantic-errors -lm -g" && ls && mv student_test.exe build/student_test.exe
      - name: Zip up output
        run: |
          cd build
          Compress-Archive -Path . -DestinationPath ../student_test.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Upload Windows Zip
          path: student_test.zip