name: Build and Release

on:
  push:
    {}
#    tags:
#      - '*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: gcc -o student_test.exe test/student_test.c && mkdir build && mv student_test.exe build/student_test.exe
      - name: Zip up output
        run: |
          cd build
          zip -r . *
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: build